I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/act1.rpy", line 52, in script
    init python:
  File "game/scripts/act1.rpy", line 55, in <module>
    renpy.say("The current directory is: {}".format(current_directory))
TypeError: say() missing 1 required positional argument: 'what'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/act1.rpy", line 52, in script
    init python:
  File "C:\Moje\Programowanie\ProjektyVSC&Cursor\TimeLoader2\basegame\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Moje\Programowanie\ProjektyVSC&Cursor\TimeLoader2\basegame\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/scripts/act1.rpy", line 55, in <module>
    renpy.say("The current directory is: {}".format(current_directory))
TypeError: say() missing 1 required positional argument: 'what'

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
Time keeper 0.9.0
Tue Dec  5 17:58:48 2023
